package com.cacanode.api.common.enums;

public enum LogAction {
    USER_LOGIN,
    USER_LOGOUT,
    DOCUMENT_UPLOAD,
    DOCUMENT_DELETE,
    USER_INVITE,
    USER_REMOVE,
    USER_INVITATION_RESENT,
    USER_INVITATION_CANCELLED,
    USER_INVITATION_ACCEPTED,
    USER_ROLE_CHANGED,
    USER_DEACTIVATED,
    USER_REACTIVATED,
    VERIFICATION_EMAIL_SENT,
    VERIFICATION_EMAIL_RESEND_REQUESTED,
    VERIFICATION_EMAIL_RESEND_LIMIT_EXCEEDED,
    LOGIN_2FA_REQUESTED,
    LOGIN_2FA_RESEND_REQUESTED,
    LOGIN_2FA_RESEND_LIMIT_EXCEEDED,
    LOGIN_2FA_VERIFIED,
    USER_SUSPENDED_VERIFICATION_ABUSE,
    CUSTOMER_ANSWER_PROMPT_UPDATED
}
