package com.cacanode.api.common.enums;

public enum LogAction {
    USER_LOGIN,
    USER_LOGOUT,
    DOCUMENT_UPLOAD,
    DOCUMENT_DELETE,
    USER_INVITE,
    USER_REMOVE,
    VERIFICATION_EMAIL_SENT,
    VERIFICATION_EMAIL_RESEND_REQUESTED,
    VERIFICATION_EMAIL_RESEND_LIMIT_EXCEEDED,
    LOGIN_2FA_REQUESTED,
    LOGIN_2FA_RESEND_REQUESTED,
    LOGIN_2FA_RESEND_LIMIT_EXCEEDED,
    LOGIN_2FA_VERIFIED,
    USER_SUSPENDED_VERIFICATION_ABUSE
}
