"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useFormatter, useTranslations } from "next-intl";
import { useSearchParams } from "next/navigation";
import { Link, useRouter } from "@/i18n/navigation";
import { useApiClient } from "@/hooks/useApiClient";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card, CardContent } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { getApplicationDetail, getInterviewAttempts, inviteApplication, jobAction, listRecruitmentApplications, listRecruitmentCandidates, listRecruitmentInterviews, listRecruitmentJobs, listRecruitmentTemplates, saveCandidate, transitionApplication, type ApplicationDetail, type CallAttempt, type RecruitmentApplication, type RecruitmentCandidate, type RecruitmentInterview, type RecruitmentJob, type RecruitmentTemplate } from "@/lib/recruitment-admin-api";

type Kind = "jobs" | "applications" | "candidates" | "templates" | "interviews" | "schedule";
type Row = RecruitmentJob | RecruitmentApplication | RecruitmentCandidate | RecruitmentTemplate | RecruitmentInterview;
const jobActions = ["publish", "pause", "close", "archive"] as const;
const statusOptions: Record<Kind, string[]> = { jobs: ["DRAFT", "PUBLISHED", "PAUSED", "CLOSED", "ARCHIVED"], applications: ["SUBMITTED", "INTERVIEW_INVITED", "INTERVIEW_SCHEDULED", "INTERVIEW_COMPLETED", "UNDER_REVIEW", "SHORTLISTED", "REJECTED", "WITHDRAWN"], candidates: [], templates: [], interviews: ["INVITED", "SCHEDULED", "IN_PROGRESS", "COMPLETED", "FAILED", "NO_ANSWER", "DECLINED", "CANCELLED", "EXPIRED"], schedule: ["SCHEDULED"] };

function rowTitle(row: Row) { if ("title" in row) return row.title; if ("fullName" in row) return row.fullName; if ("name" in row) return row.name; return row.candidateName; }
function rowSubtitle(row: Row) { if ("jobTitle" in row) return row.jobTitle; if ("email" in row) return row.email; if ("department" in row) return [row.department, row.location].filter(Boolean).join(" · "); if ("locale" in row) return row.locale; return ""; }
function rowStatus(row: Row) { if ("status" in row) return row.status; if ("archived" in row) return row.archived ? "ARCHIVED" : "ACTIVE"; return "ACTIVE"; }

export function RecruitmentListPage({ kind }: { kind: Kind }) {
  const t = useTranslations("Recruitment"); const format = useFormatter(); const { request } = useApiClient(); const search = useSearchParams(); const router = useRouter();
  const page = Number(search.get("page") ?? 0); const q = search.get("q") ?? ""; const filter = search.get("status") ?? (kind === "schedule" ? "SCHEDULED" : ""); const selected = search.get("selected");
  const [query, setQuery] = useState(q); const [rows, setRows] = useState<Row[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [detail, setDetail] = useState<ApplicationDetail | null>(null); const [attempts, setAttempts] = useState<CallAttempt[]>([]); const [candidateOpen, setCandidateOpen] = useState(false); const [candidate, setCandidate] = useState({ fullName: "", email: "", phone: "", notes: "" });
  const update = useCallback((values: Record<string, string | null>) => { const next = new URLSearchParams(search.toString()); Object.entries(values).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); router.replace(`/recruitment/${kind}?${next}`); }, [kind, router, search]);
  useEffect(() => { const timer = window.setTimeout(() => { if (query !== q) update({ q: query, page: null }); }, 300); return () => window.clearTimeout(timer); }, [q, query, update]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const common = { page, size: 20, q, status: filter || undefined }; const result = kind === "jobs" ? await listRecruitmentJobs(request, common) : kind === "applications" ? await listRecruitmentApplications(request, common) : kind === "candidates" ? await listRecruitmentCandidates(request, { page, size: 20, q }) : kind === "templates" ? await listRecruitmentTemplates(request, { page, size: 20, q }) : await listRecruitmentInterviews(request, common); setRows(result.items); setTotal(result.total); } catch (cause) { setError(cause instanceof Error ? cause.message : t("loadError")); } finally { setLoading(false); } }, [filter, kind, page, q, request, t]);
  useEffect(() => { const task = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(task); }, [load]);
  useEffect(() => { const task = window.setTimeout(() => { setDetail(null); setAttempts([]); if (!selected) return; if (kind === "applications") void getApplicationDetail(request, selected).then(setDetail).catch(() => undefined); if (kind === "interviews") void getInterviewAttempts(request, selected).then(setAttempts).catch(() => undefined); }, 0); return () => window.clearTimeout(task); }, [kind, request, selected]);
  const selectedRow = useMemo(() => rows.find((row) => row.id === selected), [rows, selected]);
  async function act(action: string) { if (!selectedRow) return; try { if (kind === "jobs") await jobAction(request, selectedRow.id, action as typeof jobActions[number]); else if (kind === "applications") { if (action === "invite") await inviteApplication(request, selectedRow.id); else await transitionApplication(request, selectedRow.id, action); } await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("loadError")); } }
  async function createCandidate() { try { await saveCandidate(request, { fullName: candidate.fullName, email: candidate.email, phone: candidate.phone || null, notes: candidate.notes || null }); setCandidateOpen(false); setCandidate({ fullName: "", email: "", phone: "", notes: "" }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("loadError")); } }
  const pages = Math.max(1, Math.ceil(total / 20));
  return <div className="space-y-4" aria-live="polite">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="text-lg font-semibold">{t(`nav.${kind}`)}</h3><p className="text-sm text-slate-500">{t(`pages.${kind}`)}</p></div><div className="flex gap-2">{kind === "candidates" && <Button onClick={() => setCandidateOpen(true)}>{t("actions.createCandidate")}</Button>}{kind === "jobs" && <Button nativeButton={false} render={<Link href="/recruitment/jobs/new" />}>{t("actions.createJob")}</Button>}{kind === "templates" && <Button nativeButton={false} render={<Link href="/recruitment/templates/new" />}>{t("actions.createTemplate")}</Button>}{kind === "schedule" && <Button variant="outline" nativeButton={false} render={<Link href="/recruitment/setup" />}>{t("nav.setup")}</Button>}</div></div>
    <div className="flex flex-wrap gap-2"><Input aria-label={t("search")} value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t("search")} className="max-w-sm" />{statusOptions[kind].length > 0 && <Select value={filter || "ALL"} onValueChange={(value) => update({ status: value === "ALL" ? null : value, page: null })}><SelectTrigger className="w-52"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">{t("allStatuses")}</SelectItem>{statusOptions[kind].map((value) => <SelectItem key={value} value={value}>{value.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select>}</div>
    {error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_380px]"><Card><CardContent className="p-0"><div className="divide-y">{rows.map((row) => <button type="button" key={row.id} onClick={() => update({ selected: row.id })} className={`flex w-full flex-wrap items-center justify-between gap-3 p-4 text-left hover:bg-slate-50 ${selected === row.id ? "bg-indigo-50" : ""}`}><span className="min-w-0"><strong className="block truncate">{rowTitle(row)}</strong><span className="block truncate text-sm text-slate-500">{rowSubtitle(row)}</span></span><span className="flex items-center gap-3"><Badge variant="outline">{rowStatus(row).replaceAll("_", " ")}</Badge>{"scheduledStartAt" in row && row.scheduledStartAt && <span className="text-xs text-slate-500">{format.dateTime(new Date(row.scheduledStartAt), { dateStyle: "short", timeStyle: "short" })}</span>}</span></button>)}{loading && <p className="p-8 text-center text-sm text-slate-500">{t("loading")}</p>}{!loading && rows.length === 0 && <p className="p-8 text-center text-sm text-slate-500">{t("empty")}</p>}</div></CardContent></Card><Card className="h-fit"><CardContent className="space-y-4 p-4">{!selectedRow && <p className="text-sm text-slate-500">{t("selectItem")}</p>}{selectedRow && <><div><h4 className="font-semibold">{rowTitle(selectedRow)}</h4><p className="text-sm text-slate-500">{rowSubtitle(selectedRow)}</p></div><Badge>{rowStatus(selectedRow).replaceAll("_", " ")}</Badge>{kind === "jobs" && <div className="flex flex-wrap gap-2">{jobActions.map((action) => <Button key={action} size="sm" variant="outline" onClick={() => void act(action)}>{t(`actions.${action}`)}</Button>)}</div>}{kind === "applications" && <ApplicationEvidence detail={detail} />}{kind === "applications" && <div className="flex flex-wrap gap-2">{["UNDER_REVIEW", "SHORTLISTED", "REJECTED"].map((action) => <Button key={action} size="sm" variant="outline" onClick={() => void act(action)}>{action.replaceAll("_", " ")}</Button>)}<Button size="sm" onClick={() => void act("invite")}>{t("actions.invite")}</Button></div>}{kind === "interviews" && <AttemptList attempts={attempts} />}{kind === "schedule" && "scheduledStartAt" in selectedRow && <div className="text-sm"><p>{selectedRow.scheduledStartAt ? format.dateTime(new Date(selectedRow.scheduledStartAt), { dateStyle: "full", timeStyle: "short" }) : t("notScheduled")}</p><p className="text-slate-500">{selectedRow.schedulingTimezone}</p></div>}</>}</CardContent></Card></div>
    <div className="flex items-center justify-between"><span className="text-sm text-slate-500">{t("pagination", { page: page + 1, pages, total })}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page <= 0} onClick={() => update({ page: String(page - 1) })}>{t("previous")}</Button><Button variant="outline" size="sm" disabled={page + 1 >= pages} onClick={() => update({ page: String(page + 1) })}>{t("next")}</Button></div></div>
    <Dialog open={candidateOpen} onOpenChange={setCandidateOpen}><DialogContent><DialogHeader><DialogTitle>{t("actions.createCandidate")}</DialogTitle><DialogDescription>{t("candidateDialog")}</DialogDescription></DialogHeader>{(["fullName", "email", "phone", "notes"] as const).map((key) => <Input key={key} placeholder={t(`fields.${key}`)} value={candidate[key]} onChange={(event) => setCandidate((value) => ({ ...value, [key]: event.target.value }))} />)}<DialogFooter><Button onClick={() => void createCandidate()} disabled={!candidate.fullName || !candidate.email}>{t("save")}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function ApplicationEvidence({ detail }: { detail: ApplicationDetail | null }) { const t = useTranslations("Recruitment"); if (!detail) return <p className="text-sm text-slate-500">{t("loading")}</p>; const selected = new Map(detail.screeningAnswers.map((answer) => [answer.questionId, answer.optionId])); return <div className="space-y-3 text-sm"><div><p className="font-medium">{detail.candidate.fullName}</p><p className="text-slate-500">{detail.candidate.email} · {detail.candidate.phone}</p></div>{detail.screeningQuestions.map((question) => <div key={question.questionId} className="rounded-md bg-slate-50 p-2"><p>{question.prompt}</p><p className="font-medium text-indigo-700">{question.options.find((option) => option.optionId === selected.get(question.questionId))?.label ?? "—"}</p></div>)}<p className="rounded-md bg-amber-50 p-2 text-xs text-amber-800">{t("advisory")}</p></div>; }
function AttemptList({ attempts }: { attempts: CallAttempt[] }) { const t = useTranslations("Recruitment"); return <div className="space-y-2"><h5 className="text-sm font-semibold">{t("callAttempts")}</h5>{attempts.map((attempt) => <div key={attempt.attemptNumber} className="rounded-md border p-2 text-xs"><div className="flex justify-between"><span>#{attempt.attemptNumber}</span><strong>{attempt.status}</strong></div>{attempt.failureCode && <p className="text-red-700">{attempt.failureCode}</p>}</div>)}{attempts.length === 0 && <p className="text-sm text-slate-500">{t("noAttempts")}</p>}</div>; }
