server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: cacanode-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO

app:
  rate-limit:
    enabled: ${PUBLIC_RATE_LIMIT_ENABLED:true}
    public-requests-per-minute: ${PUBLIC_RATE_LIMIT_PER_MINUTE:120}
