import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { PublicJobsLayout } from "@/components/recruitment/PublicJobsLayout";
import { getPublicJob } from "@/lib/recruitment-api";
import { languageAlternates, localizedPath } from "@/lib/recruitment-seo";
import { Link } from "@/i18n/navigation";
import { Button } from "@/components/ui/button";
import type { AppLocale } from "@/i18n/routing";
import NextLink from "next/link";

type Props={params:Promise<{locale:AppLocale;publicId:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {locale,publicId}=await params;try{const job=await getPublicJob(publicId);const path=`/jobs/${publicId}`;return{title:`${job.title} — ${job.companyName}`,description:job.description.slice(0,155),alternates:{canonical:localizedPath(locale,path),languages:languageAlternates(path)},openGraph:{title:job.title,description:job.description.slice(0,155),type:"website",url:localizedPath(locale,path)}};}catch{return{};}}
export default async function JobPage({params}:Props){const {locale,publicId}=await params;setRequestLocale(locale);const t=await getTranslations({locale,namespace:"Jobs.detail"});let job;try{job=await getPublicJob(publicId);}catch{notFound();}const jsonLd={"@context":"https://schema.org","@type":"JobPosting",title:job.title,description:job.description,datePosted:job.publishedAt,validThrough:job.closingAt,employmentType:job.employmentType,hiringOrganization:{"@type":"Organization",name:job.companyName},jobLocation:job.location?{"@type":"Place",address:{"@type":"PostalAddress",addressLocality:job.location}}:undefined,jobLocationType:job.workMode==="REMOTE"?"TELECOMMUTE":undefined};return <PublicJobsLayout><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,"\\u003c")}}/><article className="mx-auto max-w-3xl"><Link href="/jobs" className="text-sm font-medium text-indigo-600 hover:text-indigo-800">← {t("allJobs")}</Link><div className="mt-5 rounded-xl border bg-white p-6 shadow-sm sm:p-9"><p className="font-medium text-indigo-600">{job.companyName}</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">{job.title}</h1><div className="mt-4 flex flex-wrap gap-2 text-sm text-slate-600">{job.location&&<span>{job.location}</span>}{job.employmentType&&<span>• {job.employmentType.replaceAll("_"," ")}</span>}{job.workMode&&<span>• {job.workMode}</span>}</div><div className="mt-8 whitespace-pre-wrap leading-7 text-slate-700">{job.description}</div><div className="mt-9 flex flex-col items-start justify-between gap-4 border-t pt-6 sm:flex-row sm:items-center"><p className="text-sm text-slate-500">{t("closing",{date:new Intl.DateTimeFormat(locale,{dateStyle:"long"}).format(new Date(job.closingAt))})}</p><NextLink href={`${locale==="vi"?"/vi":""}/jobs/${publicId}/apply`}><Button className="bg-indigo-600 text-white hover:bg-indigo-700">{t("apply")}</Button></NextLink></div></div></article></PublicJobsLayout>;}
