ALTER TABLE notifications DROP CONSTRAINT notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (type IN (
    'WELCOME_EMAIL', 'LOGIN_2FA_EMAIL', 'DOCUMENT_COMPLETED', 'DOCUMENT_FAILED', 'USER_INVITED',
    'QUOTA_WARNING', 'QUOTA_EXCEEDED', 'BILLING_RENEWAL', 'BILLING_GRACE', 'TICKET_CREATED'
));
