"use client"

import { useCallback, useEffect, useState } from "react"
import { Loader2, RefreshCw } from "lucide-react"
import { useFormatter, useTranslations } from "next-intl"
import { useSearchParams } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useApiClient } from "@/hooks/useApiClient"
import { Link, useRouter } from "@/i18n/navigation"
import { getPlatformTenants, type TenantPage } from "@/lib/platform-api"

const sorts = ["name","status","plan","createdAt","updatedAt","activeUsers","documents","storageBytes","conversations","openTickets","jobs","verifiedApplications","completedInterviews"]
export default function PlatformTenantsPage() {
  const t = useTranslations("Platform.tenants")
  const format = useFormatter(), params = useSearchParams(), router = useRouter(), { request } = useApiClient()
  const page = Math.max(0, Number(params.get("page") ?? 0) || 0), size = Math.min(100, Math.max(1, Number(params.get("size") ?? 20) || 20))
  const q = (params.get("q") ?? "").slice(0, 200), status = params.get("status") ?? "", plan = params.get("plan") ?? ""
  const sort = sorts.includes(params.get("sort") ?? "") ? params.get("sort")! : "createdAt", direction = params.get("direction") === "asc" ? "asc" : "desc"
  const [search,setSearch] = useState(q), [data,setData] = useState<TenantPage|null>(null), [loading,setLoading] = useState(true), [error,setError] = useState("")
  const update = useCallback((values: Record<string,string|number>) => { const next = new URLSearchParams(params.toString()); Object.entries(values).forEach(([key,value]) => value === "" ? next.delete(key) : next.set(key,String(value))); router.replace(`/platform/tenants?${next}`) }, [params,router])
  const load = useCallback(async () => { setLoading(true); setError(""); try { setData(await getPlatformTenants(request,{page,size,q,status,plan,sort,direction})) } catch(cause){setError(cause instanceof Error?cause.message:t("loadError"))} finally{setLoading(false)} },[direction,page,plan,q,request,size,sort,status,t])
  useEffect(()=>{const id=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(id)},[load])
  const pages=Math.max(1,Math.ceil((data?.total??0)/size))
  return <div className="mx-auto max-w-7xl space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{t("title")}</h1><p className="mt-1 text-sm text-slate-600">{t("description")}</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="size-4"/>{t("refresh")}</Button></header>
    <section className="overflow-hidden rounded-xl border bg-white"><form className="flex flex-wrap gap-3 border-b p-4" onSubmit={event=>{event.preventDefault();update({q:search.trim().slice(0,200),page:0})}}><Input className="max-w-sm" value={search} onChange={e=>setSearch(e.target.value)} placeholder={t("search")}/><select value={status} onChange={e=>update({status:e.target.value,page:0})} className="rounded-md border px-3 text-sm"><option value="">{t("allStatuses")}</option>{["ACTIVE","INACTIVE","SUSPENDED"].map(x=><option key={x}>{x}</option>)}</select><select value={plan} onChange={e=>update({plan:e.target.value,page:0})} className="rounded-md border px-3 text-sm"><option value="">{t("allPlans")}</option>{["TRIAL","STARTER","PRO","BUSINESS","ENTERPRISE"].map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>update({sort:e.target.value,page:0})} className="rounded-md border px-3 text-sm">{sorts.map(x=><option key={x} value={x}>{t(`sort.${x}` as never)}</option>)}</select><select value={direction} onChange={e=>update({direction:e.target.value,page:0})} className="rounded-md border px-3 text-sm"><option value="asc">{t("ascending")}</option><option value="desc">{t("descending")}</option></select><Button variant="outline" type="submit">{t("apply")}</Button></form>
      {error&&<p role="alert" className="m-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{loading&&!data?<div className="grid h-56 place-items-center"><Loader2 className="size-7 animate-spin text-indigo-600"/></div>:(data?.items.length??0)===0?<p className="p-14 text-center text-slate-500">{t("empty")}</p>:<><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr>{["tenant","status","plan","activeUsers","documents","storage","conversations","tickets","jobs","verified","completed","created"].map(x=><th key={x} className="px-4 py-3">{t(`columns.${x}` as never)}</th>)}</tr></thead><tbody>{data?.items.map(item=><tr key={item.tenantId} className="border-t"><td className="px-4 py-3"><Link className="font-medium text-indigo-700 hover:underline" href={`/platform/tenants/${item.tenantId}`}>{item.name}</Link><p className="text-xs text-slate-400">{item.tenantId}</p></td><td className="px-4 py-3">{item.status}</td><td className="px-4 py-3">{item.plan}</td><td className="px-4 py-3">{item.activeUsers}</td><td className="px-4 py-3">{item.documents}</td><td className="px-4 py-3">{format.number(item.storageBytes/(1024*1024),{maximumFractionDigits:1})} MB</td><td className="px-4 py-3">{item.conversations}</td><td className="px-4 py-3">{item.openTickets}</td><td className="px-4 py-3">{item.jobs}</td><td className="px-4 py-3">{item.verifiedApplications}</td><td className="px-4 py-3">{item.completedInterviews}</td><td className="px-4 py-3">{format.dateTime(new Date(item.createdAt),{dateStyle:"medium"})}</td></tr>)}</tbody></table></div><div className="grid gap-3 p-4 md:hidden">{data?.items.map(item=><Link key={item.tenantId} href={`/platform/tenants/${item.tenantId}`} className="rounded-lg border p-4"><div className="flex justify-between gap-3"><strong>{item.name}</strong><span className="text-sm">{item.plan}</span></div><p className="mt-1 text-xs text-slate-500">{item.status}</p><dl className="mt-3 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-slate-500">{t("columns.activeUsers")}</dt><dd>{item.activeUsers}</dd></div><div><dt className="text-slate-500">{t("columns.documents")}</dt><dd>{item.documents}</dd></div><div><dt className="text-slate-500">{t("columns.jobs")}</dt><dd>{item.jobs}</dd></div></dl></Link>)}</div></>}
      <footer className="flex items-center justify-between border-t p-4 text-sm"><span>{t("total",{count:data?.total??0})}</span><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={page===0} onClick={()=>update({page:page-1})}>{t("previous")}</Button><span>{page+1}/{pages}</span><Button size="sm" variant="outline" disabled={page+1>=pages} onClick={()=>update({page:page+1})}>{t("next")}</Button></div></footer></section></div>
}
