export type RecruitmentCapabilities={tenantId:string;rolloutStage:'OFF'|'AUTO'|'INTERNAL'|'PILOT'|'GA';masterEnabled:boolean;publicJobsEnabled:boolean;automationEnabled:boolean;cvAiEnabled:boolean;callingEnabled:boolean;recordingEnabled:boolean;publicDiscoveryEnabled:boolean;maxInterviewDurationSeconds:number;blockers:string[]};
export type RecruitmentOverview={jobStatusCounts:Record<string,number>;applicationStatusCounts:Record<string,number>;interviewStatusCounts:Record<string,number>;upcomingInterviews:RecruitmentInterview[]};

export type ScreeningQuestion={questionId:string;prompt:string;options:{optionId:string;label:string}[];acceptedOptionIds:string[]};
export type RecruitmentJob={id:string;publicId:string;title:string;description:string;descriptionHtml:string|null;department:string|null;location:string|null;employmentType:string|null;workMode:string|null;experienceLevel:string|null;language:'vi-VN'|'en-US';status:string;cvPolicy:string;automationModeOverride:string|null;cvAiModeOverride:string|null;effectiveAutomationMode:string|null;effectiveCvAiMode:string|null;recordingEnabled:boolean;recordingRetentionDays:number;templateRevisionId:string|null;closingAt:string|null;publishedAt:string|null;pausedAt:string|null;closedAt:string|null;archivedAt:string|null;companyName:string|null;companySlug:string|null;version:number;screeningQuestions:ScreeningQuestion[];createdAt:string;updatedAt:string};
export type JobWrite={title:string;description:string;descriptionHtml:string|null;department:string|null;location:string|null;employmentType:string|null;workMode:string|null;experienceLevel:string|null;language:'vi-VN'|'en-US';cvPolicy:string;automationModeOverride:string|null;cvAiModeOverride:string|null;templateRevisionId:string|null;closingAt:string|null;screeningQuestions:ScreeningQuestion[]};
export type RecruitmentJobPreview=Pick<RecruitmentJob,'publicId'|'title'|'description'|'descriptionHtml'|'department'|'location'|'employmentType'|'workMode'|'experienceLevel'|'language'|'cvPolicy'|'status'|'publishedAt'|'closingAt'>&{tenantSlug:string;companyName:string};

export type RecruitmentApplication={id:string;jobId:string;jobTitle:string;candidateId:string;candidateName:string;candidateEmail:string;status:string;submittedAt:string|null;verifiedAt:string|null;withdrawnAt:string|null;cvPresent:boolean;cvAnalysisStatus:string;overallScore:number|null;englishBand:string|null;interviewStatus:string|null;updatedAt:string};
export type RecruitmentCandidate={id:string;fullName:string;email:string;phone:string|null;notes:string|null;createdAt:string;updatedAt:string};
export type CandidateWrite={fullName:string;email:string;phone:string|null;notes:string|null};

export type InteractionLimits={repetitionLimit:number;clarificationLimit:number;silenceTimeoutSeconds:number;silencePromptLimit:number};
export type TemplateQuestion={questionId:string;position:number;prompt:string;competency:string;rubric:string;followUpLimit:number;source:string;evidence:string|null};
export type TemplateSection={sectionId:string;position:number;kind:string;languageTag:string;durationLimitSeconds:number;transitionText:string|null;questions:TemplateQuestion[]};
export type RevisionContent={introductionText:string;disclosureText:string;closingText:string;durationLimitSeconds:number;interactionLimits:InteractionLimits;sections:TemplateSection[]};
export type TemplateCreate={name:string;description:string|null;locale:'vi-VN'|'en-US';content:RevisionContent};
export type RecruitmentTemplate={id:string;name:string;description:string|null;locale:'vi-VN'|'en-US';archived:boolean;archivedAt:string|null;latestRevisionNumber:number;version:number;createdAt:string;updatedAt:string};
export type RevisionResponse={id:string;templateId:string;revisionNumber:number;content:RevisionContent;contentSha256:string;createdAt:string};

export type RecruitmentInterview={id:string;applicationId:string;jobId:string;jobTitle:string;candidateId:string;candidateName:string;status:string;scheduledAt:string|null;scheduledStartAt:string|null;scheduledEndAt:string|null;schedulingTimezone:string|null;rescheduleCount:number;startedAt:string|null;completedAt:string|null;overallScore:number|null;englishBand:string|null;recordingEnabled:boolean;recordingRetentionDays:number;updatedAt:string};
export type RecruitmentSettings={defaultAutomationMode:string;cvAiMode:string;defaultTemplateRevisionId:string|null;recordingEnabled:boolean;recordingRetentionDays:number;schedulingTimezone:string;minimumNoticeMinutes:number;bookingHorizonDays:number;invitationLifetimeDays:number;rescheduleCutoffMinutes:number;reminderOffsetsMinutes:number[];version:number};
export type RecruitmentAvailability={timezone:string;weeklyWindows:{dayOfWeek:number;startLocal:string;endLocal:string}[];exceptions:{date:string;kind:string;startLocal:string;endLocal:string}[];version:number};
export type InterviewSlot={startAt:string;endAt:string;schedulingTimezone:string};
export type DeliveryHistoryItem={id:string;type:string;status:string;recipient:string;sentAt:string|null;failureReason:string|null;createdAt:string};
export type ApplicationDetail={application:RecruitmentApplication;candidate:RecruitmentCandidate;screeningQuestions:{questionId:string;prompt:string;options:{optionId:string;label:string}[]}[];screeningAnswers:{questionId:string;optionId:string}[]};
export type CvAnalysis={mode:string;status:string;policyVersion:string;modelVersion:string;generatedAt:string|null;summary:string|null;evidence:{anchorId:string;excerpt:string;sourceLocation:string}[];skills:{name:string;evidenceAnchorIds:string[]}[];personalizedQuestions:{questionId:string;targetSectionId:string;prompt:string;competency:string;rubric:string;evidenceAnchorIds:string[]}[];failureCode:string|null;advisoryOnly:boolean;fitScorePercent?:number|null;fitConfidence?:string|null;fitExplanation?:string|null;refreshAvailable?:boolean;refreshStatus?:string;refreshFailureCode?:string|null};
export type CallAttempt={attemptNumber:number;status:string;createdAt:string;updatedAt:string;answeredAt:string|null;consentedAt:string|null;terminalAt:string|null;failureCode:string|null};
export type DialEligibility={allowed:boolean;reason:string|null;windowOpensAt:string|null;windowClosesAt:string|null;serverTime:string};
export type DialResponse={attemptId:string;status:string;failureCode:string|null;acceptedAt:string};
export type InterviewTranscript={deliveryStatus:string;expectedTurnCount:number;persistedTurnCount:number;page:number;size:number;turns:{turnId:string;sequence:number;speaker:string;turnKind:string;sectionId:string|null;questionId:string|null;languageTag:string;transcript:string}[]};
export type InterviewResult={terminalKind:string;deliveryStatus:string;completionReason:string|null;failureCode:string|null;partial:boolean;overallScore:number|null;englishBand:string|null;advisoryOnly:boolean;englishWarning:string;sections:{sectionId:string;kind:string;status:string;questions:{questionId:string;status:string;score:number|null;evidenceTurnIds:string[]}[]}[]};
export type InterviewRecording={recordingId:string;state:string;contentType:string|null;sizeBytes:number|null;retainedUntil:string|null;readyAt:string|null;deletedAt:string|null};
