"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { Loader2, RefreshCw } from "lucide-react"
import { useFormatter, useTranslations } from "next-intl"
import { useSearchParams } from "next/navigation"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useApiClient } from "@/hooks/useApiClient"
import { Link, useRouter } from "@/i18n/navigation"
import { getPlatformJobs, type PlatformJobItem, type PlatformJobPage } from "@/lib/platform-api"

const statuses=["DRAFT","PUBLISHED","PAUSED","CLOSED","ARCHIVED"]
const employmentTypes=["FULL_TIME","PART_TIME","CONTRACT","TEMPORARY","INTERNSHIP"]
const workModes=["ONSITE","REMOTE","HYBRID"]
const sorts=["updatedAt","title","companyName","status","publishedAt","closingAt","applications","interviews","visibility"]
type Translator=(key:string,values?:Record<string,unknown>)=>string

export default function PlatformJobsPage(){
 const params=useSearchParams()
 return <PlatformJobsContent key={params.toString()}/>
}

function PlatformJobsContent(){
 const typedT=useTranslations("Platform.jobs"),t=typedT as unknown as Translator,format=useFormatter(),params=useSearchParams(),router=useRouter(),{request}=useApiClient()
 const page=Math.max(0,Number(params.get("page")??0)||0),size=Math.min(100,Math.max(1,Number(params.get("size")??20)||20))
 const values=useMemo(()=>({tenantId:params.get("tenantId")??"",status:params.get("status")??"",q:params.get("q")??"",language:params.get("language")??"",department:params.get("department")??"",location:params.get("location")??"",employmentType:params.get("employmentType")??"",workMode:params.get("workMode")??"",visibility:params.get("visibility")??"",closingFrom:params.get("closingFrom")??"",closingTo:params.get("closingTo")??"",updatedFrom:params.get("updatedFrom")??"",updatedTo:params.get("updatedTo")??"",sort:sorts.includes(params.get("sort")??"")?params.get("sort")!:"updatedAt",direction:params.get("direction")==="asc"?"asc":"desc"}),[params])
 const [filters,setFilters]=useState(values),[data,setData]=useState<PlatformJobPage|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("")
 const update=useCallback((changes:Record<string,string|number>)=>{const next=new URLSearchParams(params.toString());Object.entries(changes).forEach(([key,value])=>value===""?next.delete(key):next.set(key,String(value)));router.replace(`/platform/jobs${next.size?`?${next}`:""}`)},[params,router])
 const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await getPlatformJobs(request,{...values,page,size}))}catch(cause){setError(cause instanceof Error?cause.message:t("loadError"))}finally{setLoading(false)}},[page,request,size,t,values])
 useEffect(()=>{const id=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(id)},[load])
 const submit=(event:React.FormEvent)=>{event.preventDefault();update({...filters,q:filters.q.trim().slice(0,200),page:0})},pages=Math.max(1,Math.ceil((data?.total??0)/size))
 return <div className="mx-auto max-w-[1500px] space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{t("title")}</h1><p className="mt-1 text-sm text-slate-600">{t("description")}</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="size-4"/>{t("refresh")}</Button></header>
  <section className="overflow-hidden rounded-xl border bg-white"><form onSubmit={submit} className="grid gap-3 border-b p-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><Input value={filters.q} maxLength={200} onChange={e=>setFilters({...filters,q:e.target.value})} placeholder={t("filters.search")}/><Input value={filters.tenantId} onChange={e=>setFilters({...filters,tenantId:e.target.value})} placeholder={t("filters.tenant")}/><Filter value={filters.status} onChange={status=>setFilters({...filters,status})} label={t("filters.status")} items={statuses}/><Filter value={filters.visibility} onChange={visibility=>setFilters({...filters,visibility})} label={t("filters.visibility")} items={["VISIBLE","HIDDEN"]}/><Filter value={filters.language} onChange={language=>setFilters({...filters,language})} label={t("filters.language")} items={["en-US","vi-VN"]}/><Input value={filters.department} onChange={e=>setFilters({...filters,department:e.target.value})} placeholder={t("filters.department")}/><Input value={filters.location} onChange={e=>setFilters({...filters,location:e.target.value})} placeholder={t("filters.location")}/><Filter value={filters.employmentType} onChange={employmentType=>setFilters({...filters,employmentType})} label={t("filters.employmentType")} items={employmentTypes}/><Filter value={filters.workMode} onChange={workMode=>setFilters({...filters,workMode})} label={t("filters.workMode")} items={workModes}/><Input value={filters.closingFrom} onChange={e=>setFilters({...filters,closingFrom:e.target.value})} placeholder={t("filters.closingFrom")}/><Input value={filters.closingTo} onChange={e=>setFilters({...filters,closingTo:e.target.value})} placeholder={t("filters.closingTo")}/><Input value={filters.updatedFrom} onChange={e=>setFilters({...filters,updatedFrom:e.target.value})} placeholder={t("filters.updatedFrom")}/><Input value={filters.updatedTo} onChange={e=>setFilters({...filters,updatedTo:e.target.value})} placeholder={t("filters.updatedTo")}/><Filter value={values.sort} onChange={sort=>update({sort,page:0})} label={t("filters.sort")} items={sorts} translate={item=>t(`sort.${item}` as never)}/><Filter value={values.direction} onChange={direction=>update({direction,page:0})} label={t("filters.direction")} items={["desc","asc"]} translate={item=>t(item as "asc"|"desc")}/><div className="flex gap-2"><Button type="submit">{t("apply")}</Button><Button type="button" variant="outline" onClick={()=>router.replace("/platform/jobs")}>{t("clear")}</Button></div></form>
   {error&&<p role="alert" className="m-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{loading&&!data?<div className="grid h-60 place-items-center"><Loader2 aria-label={t("loading")} className="size-7 animate-spin text-indigo-600"/></div>:(data?.items.length??0)===0?<p className="p-16 text-center text-slate-500">{t("empty")}</p>:<><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr>{["job","tenant","lifecycle","visibility","metadata","published","closing","updated","applications","interviews"].map(key=><th key={key} className="px-4 py-3">{t(`columns.${key}` as never)}</th>)}</tr></thead><tbody>{data?.items.map(job=><JobRow key={job.jobId} job={job} format={format} t={t}/>)}</tbody></table></div><div className="grid gap-3 p-4 lg:hidden">{data?.items.map(job=><JobCard key={job.jobId} job={job} format={format} t={t}/>)}</div></>}
   <footer className="flex flex-wrap items-center justify-between gap-3 border-t p-4 text-sm"><span>{t("total",{count:data?.total??0})}</span><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={page===0} onClick={()=>update({page:page-1})}>{t("previous")}</Button><span>{page+1}/{pages}</span><Button size="sm" variant="outline" disabled={page+1>=pages} onClick={()=>update({page:page+1})}>{t("next")}</Button></div></footer></section></div>
}

function Filter({value,onChange,label,items,translate=(item)=>item}:{value:string;onChange:(value:string)=>void;label:string;items:string[];translate?:(item:string)=>string}){return <select aria-label={label} value={value} onChange={e=>onChange(e.target.value)} className="h-9 rounded-md border bg-white px-3 text-sm"><option value="">{label}</option>{items.map(item=><option key={item} value={item}>{translate(item)}</option>)}</select>}
function VisibilityBadge({job,t}:{job:PlatformJobItem;t:Translator}){return <Badge variant="outline" className={job.visibleOnPublicBoard?"border-emerald-200 bg-emerald-50 text-emerald-800":job.discoverable?"border-amber-200 bg-amber-50 text-amber-800":"border-slate-200 bg-slate-50 text-slate-600"}>{job.visibleOnPublicBoard?t("visibility.public"):job.discoverable?t("visibility.discoverableHidden"):t("visibility.hidden")}</Badge>}
function lifecycleClass(status:string){return status==="PUBLISHED"?"border-blue-200 bg-blue-50 text-blue-800":status==="DRAFT"?"border-slate-200 bg-slate-50 text-slate-700":status==="PAUSED"?"border-amber-200 bg-amber-50 text-amber-800":"border-rose-200 bg-rose-50 text-rose-800"}
function JobRow({job,format,t}:{job:PlatformJobItem;format:ReturnType<typeof useFormatter>;t:Translator}){return <tr className="border-t align-top"><td className="px-4 py-3"><Link href={`/platform/jobs/${job.jobId}`} className="font-semibold text-indigo-700 hover:underline">{job.title}</Link><p className="mt-1 text-xs text-slate-400">{job.jobId}</p><p className="text-xs text-slate-500">{job.frozenCompanyName??t("neverPublished")}</p></td><td className="px-4 py-3"><Link href={`/platform/tenants/${job.tenantId}`} className="text-indigo-700 hover:underline">{job.tenantId}</Link></td><td className="px-4 py-3"><Badge variant="outline" className={lifecycleClass(job.status)}>{t(`status.${job.status}`)}</Badge></td><td className="px-4 py-3"><VisibilityBadge job={job} t={t}/></td><td className="px-4 py-3 text-slate-600">{[job.department,job.location,job.language,job.employmentType,job.workMode,job.experienceLevel].filter(Boolean).join(" · ")||"—"}</td><DateCell value={job.publishedAt} format={format}/><DateCell value={job.closingAt} format={format}/><DateCell value={job.updatedAt} format={format}/><td className="px-4 py-3">{format.number(job.totalApplications)}</td><td className="px-4 py-3">{format.number(job.totalInterviews)}</td></tr>}
function JobCard({job,format,t}:{job:PlatformJobItem;format:ReturnType<typeof useFormatter>;t:Translator}){return <article className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/platform/jobs/${job.jobId}`} className="font-semibold text-indigo-700">{job.title}</Link><p className="text-sm text-slate-500">{job.frozenCompanyName??t("neverPublished")}</p></div><div className="flex flex-wrap gap-1"><Badge variant="outline" className={lifecycleClass(job.status)}>{t(`status.${job.status}`)}</Badge><VisibilityBadge job={job} t={t}/></div></div><p className="mt-3 text-sm text-slate-600">{[job.department,job.location,job.language,job.employmentType,job.workMode].filter(Boolean).join(" · ")||"—"}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-500">{t("columns.updated")}</dt><dd>{date(job.updatedAt,format)}</dd></div><div><dt className="text-slate-500">{t("columns.closing")}</dt><dd>{date(job.closingAt,format)}</dd></div><div><dt className="text-slate-500">{t("columns.applications")}</dt><dd>{format.number(job.totalApplications)}</dd></div><div><dt className="text-slate-500">{t("columns.interviews")}</dt><dd>{format.number(job.totalInterviews)}</dd></div></dl></article>}
function DateCell({value,format}:{value:string|null;format:ReturnType<typeof useFormatter>}){return <td className="px-4 py-3 whitespace-nowrap">{date(value,format)}</td>}
function date(value:string|null,format:ReturnType<typeof useFormatter>){return value?format.dateTime(new Date(value),{dateStyle:"medium",timeStyle:"short"}):"—"}
