"use client"

import { useCallback, useEffect, useState } from "react"
import { AlertTriangle, Loader2, RefreshCw } from "lucide-react"
import { useFormatter, useTranslations } from "next-intl"
import { useParams } from "next/navigation"
import { Button } from "@/components/ui/button"
import { useApiClient } from "@/hooks/useApiClient"
import { Link } from "@/i18n/navigation"
import { getPlatformTenant, type Quota, type TenantDetail } from "@/lib/platform-api"

export default function PlatformTenantDetailPage() {
  const t=useTranslations("Platform.tenantDetail"),failureT=useTranslations("Platform.failures"),format=useFormatter(),params=useParams<{tenantId:string}>(),{request}=useApiClient()
  const [data,setData]=useState<TenantDetail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("")
  const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await getPlatformTenant(request,params.tenantId))}catch(cause){setError(cause instanceof Error?cause.message:t("loadError"))}finally{setLoading(false)}},[params.tenantId,request,t])
  useEffect(()=>{const id=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(id)},[load])
  if(loading&&!data)return <div className="grid h-72 place-items-center"><Loader2 className="size-8 animate-spin text-indigo-600"/></div>
  if(error&&!data)return <p role="alert" className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p>
  if(!data)return null
  const aggregates=Object.entries(data.aggregates)
  return <div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap justify-between gap-3"><div><Link href="/platform/tenants" className="text-sm text-indigo-700">← {t("back")}</Link><h1 className="mt-2 text-2xl font-bold">{data.name}</h1><p className="mt-1 text-sm text-slate-500">{data.tenantId} · {data.status} · {data.plan}</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="size-4"/>{t("refresh")}</Button></header>
    {data.partial&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><div className="flex gap-2"><AlertTriangle className="size-4"/><strong>{t("partial")}</strong></div><ul className="mt-2 list-disc pl-6">{data.warnings.map((warning,index)=><li key={`${warning.code}-${index}`}>{t(`warnings.${warning.code}` as never)}{warning.source?` (${warning.source})`:""}</li>)}</ul></div>}
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{aggregates.map(([key,value])=><article key={key} className="rounded-xl border bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{t(`aggregates.${key}` as never)}</p><p className="mt-2 text-2xl font-bold">{key==="storageBytes"?format.number(Number(value)/(1024*1024),{maximumFractionDigits:1})+" MB":format.number(Number(value))}</p></article>)}</section>
    <section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-semibold">{t("billing.title")}</h2>{data.billing&&<p className="text-sm text-slate-500">{data.billing.plan} · {data.billing.status}</p>}</div>{data.billing&&<span className="text-xs text-slate-500">{format.dateTime(new Date(data.billing.periodStart),{dateStyle:"medium"})} – {format.dateTime(new Date(data.billing.periodEnd),{dateStyle:"medium"})}</span>}</div>{data.billing?<div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Object.entries(data.billing.quotas).map(([key,quota])=><QuotaCard key={key} name={t(`quotas.${key}` as never)} quota={quota}/>)}</div>:<p className="mt-4 text-sm text-slate-500">{t("billing.unavailable")}</p>}</section>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{t("recruitment.title")}</h2>{data.recruitment?<div className="mt-4 flex flex-wrap gap-2"><Badge label={data.recruitment.rolloutStage} active/><Badge label={t("recruitment.master")} active={data.recruitment.masterEnabled}/><Badge label={t("recruitment.automation")} active={data.recruitment.automationEnabled}/><Badge label={t("recruitment.cvAi")} active={data.recruitment.cvAiEnabled}/><Badge label={t("recruitment.calling")} active={data.recruitment.callingEnabled}/><Badge label={t("recruitment.recording")} active={data.recruitment.recordingEnabled}/><Badge label={t("recruitment.discovery")} active={data.recruitment.publicDiscoveryEnabled}/></div>:<p className="mt-4 text-sm text-slate-500">{t("recruitment.unavailable")}</p>}</section>
    <section className="rounded-xl border bg-white p-5"><div className="flex justify-between"><h2 className="font-semibold">{t("failures.title")}</h2><Link href={`/platform/failures?tenantId=${data.tenantId}`} className="text-sm text-indigo-700">{t("failures.viewAll")}</Link></div>{data.recentFailures.length===0?<p className="mt-4 text-sm text-slate-500">{t("failures.empty")}</p>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="text-slate-500"><tr><th className="py-2">{t("failures.source")}</th><th>{t("failures.code")}</th><th>{t("failures.state")}</th><th>{failureT("columns.resource")}</th><th>{t("failures.attempts")}</th><th>{t("failures.lastSeen")}</th></tr></thead><tbody>{data.recentFailures.map(item=><tr key={`${item.source}-${item.failureId}`} className="border-t align-top"><td className="py-3">{failureT(`sources.${item.source}` as never)}</td><td><strong>{failureT(`codes.${item.errorCode}` as never)}</strong><p className="mt-1 max-w-sm text-xs text-slate-500">{failureT("explanation",{code:failureT(`codes.${item.errorCode}` as never)})}</p></td><td>{failureT(`states.${item.state}` as never)}</td><td>{item.resourceType==="JOB"&&item.resourceId?<Link href={`/platform/jobs/${item.resourceId}`} className="text-indigo-700 hover:underline">{failureT("resourceTypes.JOB")}</Link>:failureT(`resourceTypes.${item.resourceType}` as never)}</td><td>{item.attempts}</td><td>{format.dateTime(new Date(item.lastSeenAt),{dateStyle:"medium",timeStyle:"short"})}</td></tr>)}</tbody></table></div>}</section>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{t("freshness")}</h2><dl className="mt-4 grid gap-2 sm:grid-cols-3">{Object.entries(data.freshness.projections).map(([key,value])=><div key={key} className="rounded bg-slate-50 p-3"><dt className="text-xs uppercase text-slate-500">{key}</dt><dd className="mt-1 text-sm">{value?format.dateTime(new Date(value),{dateStyle:"medium",timeStyle:"short"}):t("never")}</dd></div>)}</dl></section>
  </div>
}

function QuotaCard({name,quota}:{name:string;quota:Quota}) { const format=useFormatter(),percent=quota.utilizationPercentage??0; return <article className={`rounded-lg border p-4 ${quota.overLimit?"border-red-300 bg-red-50":""}`}><div className="flex justify-between gap-2"><strong className="text-sm">{name}</strong><span className="text-sm">{quota.unlimited?"∞":`${format.number(percent,{maximumFractionDigits:1})}%`}</span></div><p className="mt-2 text-xs text-slate-500">{format.number(quota.used)} + {format.number(quota.reserved)} / {quota.limit===null?"∞":format.number(quota.limit)}</p>{!quota.unlimited&&<div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div className={`h-full ${quota.overLimit?"bg-red-600":"bg-indigo-600"}`} style={{width:`${Math.min(100,percent)}%`}}/></div>}</article> }
function Badge({label,active}:{label:string;active:boolean}) { return <span className={`rounded-full px-3 py-1 text-xs font-medium ${active?"bg-emerald-100 text-emerald-800":"bg-slate-100 text-slate-500"}`}>{label}</span> }
