import * as Crypto from 'expo-crypto';
import type { JobWrite,RecruitmentJob,RecruitmentTemplate,RevisionContent,ScreeningQuestion,TemplateCreate,TemplateQuestion,TemplateSection } from '@/features/recruitment/types';

export function newId(){return Crypto.randomUUID()}
export function newScreeningQuestion():ScreeningQuestion{const first=newId();const second=newId();return {questionId:newId(),prompt:'',options:[{optionId:first,label:''},{optionId:second,label:''}],acceptedOptionIds:[first]}}
export function emptyJob():JobWrite{return {title:'',description:'',descriptionHtml:null,department:null,location:null,employmentType:null,workMode:null,experienceLevel:null,language:'en-US',cvPolicy:'OPTIONAL',automationModeOverride:null,cvAiModeOverride:null,templateRevisionId:null,closingAt:null,screeningQuestions:[]}}
export function jobToWrite(job:RecruitmentJob):JobWrite{return {title:job.title,description:job.description,descriptionHtml:job.descriptionHtml,department:job.department,location:job.location,employmentType:job.employmentType,workMode:job.workMode,experienceLevel:job.experienceLevel,language:job.language,cvPolicy:job.cvPolicy,automationModeOverride:job.automationModeOverride,cvAiModeOverride:job.cvAiModeOverride,templateRevisionId:job.templateRevisionId,closingAt:job.closingAt,screeningQuestions:job.screeningQuestions}}
export function validateJob(value:JobWrite,publishing=false){if(!value.title.trim()||!value.description.trim())return 'titleDescription';if(publishing&&(!value.templateRevisionId||!value.closingAt))return 'publishRequirements';if(value.closingAt&&new Date(value.closingAt).getTime()<=Date.now())return 'futureClosing';if(value.screeningQuestions.length>10)return 'screeningLimit';for(const question of value.screeningQuestions){if(!question.prompt.trim()||question.options.length<2||question.options.some(option=>!option.label.trim())||!question.acceptedOptionIds.length)return 'screeningInvalid'}return null}

export function newTemplateQuestion():TemplateQuestion{return {questionId:newId(),position:1,prompt:'',competency:'',rubric:'',followUpLimit:1,source:'TEMPLATE',evidence:null}}
export function newTemplateSection(locale:'vi-VN'|'en-US'):TemplateSection{return {sectionId:newId(),position:1,kind:'CORE',languageTag:locale,durationLimitSeconds:300,transitionText:null,questions:[newTemplateQuestion()]}}
export function initialContent(locale:'vi-VN'|'en-US'):RevisionContent{return {introductionText:locale==='vi-VN'?'Xin chào và cảm ơn bạn đã tham gia phỏng vấn.':'Hello and thank you for joining this interview.',disclosureText:locale==='vi-VN'?'Cuộc phỏng vấn có thể được ghi âm theo chính sách của công ty.':'This interview may be recorded under company policy.',closingText:locale==='vi-VN'?'Cảm ơn bạn đã dành thời gian.':'Thank you for your time.',durationLimitSeconds:600,interactionLimits:{repetitionLimit:2,clarificationLimit:2,silenceTimeoutSeconds:12,silencePromptLimit:2},sections:[newTemplateSection(locale)]}}
export function emptyTemplate():TemplateCreate{return {name:'',description:null,locale:'en-US',content:initialContent('en-US')}}
export function templateFromRecord(record:RecruitmentTemplate,content:RevisionContent):TemplateCreate{return {name:record.name,description:record.description,locale:record.locale,content}}
export function normalizeContent(content:RevisionContent):RevisionContent{return {...content,sections:content.sections.map((section,sectionIndex)=>({...section,position:sectionIndex+1,questions:section.questions.map((question,questionIndex)=>({...question,position:questionIndex+1}))}))}}
export function validateTemplate(value:TemplateCreate,maxDuration=3600){if(!value.name.trim())return 'templateName';if(!value.content.introductionText.trim()||!value.content.disclosureText.trim()||!value.content.closingText.trim())return 'spokenText';if(value.content.durationLimitSeconds<1||value.content.durationLimitSeconds>maxDuration)return 'duration';if(!value.content.sections.length)return 'sections';for(const section of value.content.sections){if(!section.questions.length||section.durationLimitSeconds<1)return 'sections';for(const question of section.questions){if(!question.prompt.trim()||!question.competency.trim()||!question.rubric.trim())return 'questions'}}return null}
